-- 1. Create a table for public profiles
create table profiles (
  id uuid references auth.users not null primary key,
  updated_at timestamp with time zone,
  username text unique,
  avatar_url text,
  
  constraint username_length check (char_length(username) >= 3)
);
ALTER TABLE profiles 
ADD COLUMN IF NOT EXISTS selected_avatar_id INTEGER DEFAULT 1,
ADD COLUMN IF NOT EXISTS unlocked_avatars INTEGER[] DEFAULT ARRAY[1];
-- 2. Create a table for high scores
create table scores (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  wpm integer not null,
  accuracy numeric(5,2) not null, -- Stores up to 100.00
  mode text not null, -- 'time' or 'words' (legacy: 'time 60')
  test_limit integer, -- seconds for 'time' or word count for 'words'
  language text default 'english'
);

-- 3. Set up Row Level Security (RLS)
alter table profiles enable row level security;
alter table scores enable row level security;

-- 4. Policies for Profiles
create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- 5. Policies for Scores
create policy "Scores are viewable by everyone."
  on scores for select
  using ( true );

create policy "Users can insert their own scores."
  on scores for insert
  with check ( auth.uid() = user_id );

-- 6. Trigger to automatically create a profile on Signup
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, username)
  values (new.id, new.raw_user_meta_data->>'username');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 7. Backfill/migration helpers
-- Add column if not exists (safe for reruns)
alter table if exists scores
  add column if not exists test_limit integer;

-- Optional index to accelerate leaderboard filters
create index if not exists scores_mode_limit_idx on scores (mode, test_limit);
